made a new branch with only user provider
NSS-Day-Cohort-42/rare-media-moguls pull request #94
Opened 2020-10-22 20:24 UTC by ConnorBlakeney

#### Changes Made
1. Added file `UserProvider.js` to `users` directory.
.
​
#### Steps to Review
1. Checkout this branch locally and run the application.
```
git fetch --all
git checkout cb-user-provider-2
```
2. Run the application.
```
npm start
```
3. Open a new Terminal tab (⌘T) and navigate to the server directory.
```
..
server
```
4. Initialize virtual environment, and run the server.
```
pipenv shell
watchgod request_handler.main
```
5. Test app functionality. 
> When user clicks on `New Post`, they should be redirected to a the PostForm page
> When user enters information into the form fields and clicks `Save`, the post database should be updated with new post object and user should be redirected to the PostDetails page to view the post they just created.
6. View code file.
> Confirm file modifications are present as indicated above.
> Confirm no unused code or extraneous comments exist.

2020-10-22 20:26 UTC, heymonicakay requested changes
One last thing! Could you remove the comments? They're not really necessary, and the last one isn't related to this file. Other than that, this looks good!

2020-10-22 20:41 UTC, ConnorBlakeney commented
removed comments from user provider

2020-10-22 20:52 UTC, Raparker88 approved these changes

2020-10-23 14:18 UTC, samanthajmaas approved these changes

2020-10-23 14:18 UTC, samanthajmaas approved these changes

2020-10-23 14:20 UTC, merged